datasets:
  - name: "infinity_instruct"
    path: "BAAI/Infinity-Instruct"

models:
  - name: "microsoft/Phi-3-mini-4k-instruct-gguf"
    path: "Phi-3-mini-4k-instruct-q4.gguf"
    parameters:
      temperature: 0.7
      max_length: 512
      top_p: 0.9
  - name: "MaziyarPanahi/Yi-Coder-1.5B-Chat-GGUF"
    path: "Yi-Coder-1.5B-Chat.Q4_K_M.gguf"
    parameters:
      temperature: 1.0
      max_length: 512
      top_p: 0.9


evaluator_model:
  name: "google/gemma-2-2b-it-gguf"
  path: "google/gemma-2-2b-it-gguf"
  parameters:
    temperature: 0.2
    max_length: 128

global_parameters:
  batch_size: 32
